### ISSUE TITLE
Resubmit to App Store?

### ISSUE THREAD

**Issue by mrmarcsmith** [nathantannar4/Parse-Dashboard-for-iOS#13]
Hi @nathantannar4,

Do you have plans to release this app to the App Store in the near term? If not, Do you have any objections to me submitting it so this project can once again be used by the public? I use this app often and after getting a new phone I discovered it was no longer available for download which lead me here but I imagine a lot more people just didn't have the time/resources to investigate further but would love to use the app.

**Comment by nathantannar4** [comment]
Hi @mrmarcsmith sorry I don't check GitHub very often these days. I would be ok with you posting it on the AppStore, provided it still attributes the open source project and by extension myself as the author.

**Comment by mrmarcsmith** [comment]
Sounds Good! I will keep your copyright/logo and links to the Project
