### ISSUE TITLE
Is there a way to have an object also display empty/nil columns?

### ISSUE THREAD

**Issue by btcnewsapp** [nathantannar4/Parse-Dashboard-for-iOS#3]
Now that objects can be edited, it would be nice if they also displayed nil columns so they can also be edited. Without being too familiar with the inner workings of parse dashboard, I found no way to enable that. Currently fields with nil value do not show up at all on the object view (though they can be seen in the preview)

Thanks!

**Comment by nathantannar4** [comment]
Thanks for bringing that bug to my attention! I will patch it in the next release

**Comment by nathantannar4** [comment]
Looking at the raw data I believe the reason that is the case is that Parse Server does not return a JSON object with a nil column. It can be fixed by using the classes schema object.

**Comment by btcnewsapp** [comment]
Hi Nathan,
Thanks for your very fast response! I assumed it was something along those lines, but as I downloaded the app from the store rather than github, did not dig in to it. I find the app very useful, and the only one that actually does the job, so thanks. And not to push my luck, but a nice feature (though somewhat bigger undertaking) would be to sync saved queries between iOS devices…  😊


Thanks again!


  …tal

——

For all your Bitcoin & Cryptocurrency news
BTCnews for iOS - http://apple.co/1GlPVnz
Web - http://btcnews.emoof.com
FB - https://www.facebook.com/btcnewsapp
Twitter @btcnewsapp - https://twitter.com/btcnewsapp
Instagram - https://www.instagram.com/btcnewsapp/
eMail - btcnews@emoof.com


On 9 September 2017 at 23:17:33, Nathan Tannar (notifications@github.com) wrote:

Looking at the raw data I believe the reason that is the case is that Parse Server does not return a JSON object with a nil column. It can be fixed by using the classes schema object.

**Comment by nathantannar4** [comment]
Glad you like it! Leave me a star 😊
