### ISSUE TITLE
No Longer Available on the App Store

### ISSUE THREAD

**Issue by nathantannar4** [nathantannar4/Parse-Dashboard-for-iOS#5]
While Parse Dashboard for iOS is no longer available on the App Store, I have updated it to be fully compatible with iOS 11s new UI elements and the iPhone X

**Comment by funkenstrahlen** [comment]
Why did you remove it from the App Store?

**Comment by nathantannar4** [comment]
Didn't renew my developer membership :( very expensive as I wasn't recuperating my costs

**Comment by funkenstrahlen** [comment]
I will try the App in the next days. Maybe I can bring it back in the App Store. Regarding the MIT license this should be possible.

**Comment by funkenstrahlen** [comment]
Feels weird to put an App in the store I did not help to develop though.

**Comment by nathantannar4** [comment]
Please try it and let me know what you think. I have been looking into In-App Purchases and plan on relaunching it in the new year with donation buttons, so I would ask you not to submit it yourself

**Comment by funkenstrahlen** [comment]
If you plan to submit to the App Store yourself I will not do this. Feels better if you do it because you put all the work into it. I do not want to get credit for something I did not do.

First impression on short test:
* I miss a real nice view to enter my server credentials. Simple alert works but feels not polished. Maybe take a look at eureka framework.
* Missing a way to edit existing server credentials. Especially annoying if you have an error in your keys and can not connect

**Comment by nathantannar4** [comment]
Thanks for the feedback! By the way, you can edit the server info. Each cell has a long tap gesture. Try holding on the cell. This is the same for cells across the app because it uses a `UICollectionView`

**Comment by nathantannar4** [comment]
I just updated it to use `Former` for entering server credentials :)

**Comment by funkenstrahlen** [comment]
> Thanks for the feedback! By the way, you can edit the server info. Each cell has a long tap gesture. Try holding on the cell. This is the same for cells across the app because it uses a UICollectionView

Oh that's interesting. Did not discover that by myself. Maybe there is a way to make editing the credentials more discoverable for the user.

> I just updated it to use Former for entering server credentials :)

Happy to hear! Would be happy to be a TestFlight user.

**Comment by nathantannar4** [comment]
I shall implement a tutorial!

**Comment by funkenstrahlen** [comment]
I honestly do not think a tutorial is a good idea. The app should be intuitive so no tutorial is required.

**Comment by nathantannar4** [comment]
@funkenstrahlen Made a lot of updates, let me know if you have any new feedback!

**Comment by funkenstrahlen** [comment]
Will take a look as soon as I find some time :)

**Comment by funkenstrahlen** [comment]
* Why do you use a custom image picker and not the system default?
* The new view to add configuration is great.
* Get rid of the oldschool save icon. Just put save as Text there.
* The navigation view header feels weird. Is it custom implemented? Why not use iOS default?
* Custom tab bar in settings view feels unnecessary.
* Rename biometric authentication to actual Face ID or Touch ID. 
* Creating new configuration with an url scheme is a great idea.
* The view when I launch the app for the first time is unnecessary in my eyes. Does not offer any useful additional information and just prevents me to get started fast
* The tutorial you looks nice but in my eyes there should not be any tutorial at all. The only really useful explanation in the tutorial is the edit functionality for an existing configuration. The other explanations are not really required in my eyes. I think editing an existing configuration should not be done via long press. Recommendation: add a swipe action like in Apple mail to edit. Also add a button in the configuration detail view to edit the configuration. The you have one shortcut way and one easy discoverable way to do it.
* 3D Touch quick actions does have Home action two times on my device.

**Comment by nathantannar4** [comment]
Thanks I will take some of those into consideration

**Comment by funkenstrahlen** [comment]
Great! Please do not see my feedback as critique only. I appreciate your work on the app! I am just trying to give you honest feedback on what I think could be improved.
